<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class GJAddAmountToFulfill extends Migration {

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up() {
        try {
            DB::beginTransaction();

            Schema::table('tblACC_GJHeader', function ($table) {
                if (!Schema::hasColumn('tblACC_GJHeader', 'GJ_AutoGenerated')) {
                    $table->boolean('GJ_AutoGenerated')->default(false);
                }
            });

            Schema::table('tblACC_GJDetail', function ($table) {
                if (!Schema::hasColumn('tblACC_GJDetail', 'GJD_AmountToBreakdown')) {
                    $table->decimal('GJD_AmountToBreakdown', 30, 12)->default(0);
                }

                if (!Schema::hasColumn('tblACC_GJDetail', 'GJD_BalanceCopy')) {
                    $table->boolean('GJD_BalanceCopy')->default(false);
                }
            });

            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
            throw $e;
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() {
        try {
            DB::beginTransaction();

            Schema::table('tblACC_GJHeader', function ($table) {
                if (Schema::hasColumn('tblACC_GJHeader', 'GJ_AutoGenerated')) {
                    $table->dropColumn('GJ_AutoGenerated');
                }
            });

            Schema::table('tblACC_GJDetail', function ($table) {
                if (Schema::hasColumn('tblACC_GJDetail', 'GJD_AmountToBreakdown')) {
                    $table->dropColumn('GJD_AmountToBreakdown');
                }

                if (Schema::hasColumn('tblACC_GJDetail', 'GJD_BalanceCopy')) {
                    $table->dropColumn('GJD_BalanceCopy');
                }
            });

            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
            throw $e;
        }
    }

}
